### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by andrewtmendoza** [SAP/sqlalchemy-hana#10]
I am receiving the following error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 259: invalid continuation byte

Is there a way to specify the encoding/charset?

**Comment by jarus** [comment]
The encoding is normally part of the underlying database driver. Which driver did you use? Do you maybe have a short code snippet to reproduce the issue?

**Comment by andrewtmendoza** [comment]
I am using PyHDB as the driver:

```
from sqlalchemy import create_engine

engine = create_engine('hana+pyhdb://username:password@example.com:30015')
connection = engine.connect()
result = connection.execute("select description from cases")
for row in result:
    print(row['description'])
connection.close()
```
