### ISSUE TITLE
Error while using sqlalchemy-hana

### ISSUE THREAD

**Issue by Burhanahmedkhan** [SAP/sqlalchemy-hana#11]
Hi,
I am trying to execute the below line

engine = create_engine('hana://SYSTEM:manager@10.100.0.10:30015')

And i get the below error--

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:hana

I am not able to understand the error, any idea?

**Comment by jarus** [comment]
Did you installed the python package via `pip install sqlalchemy-hana`?
Sounds like the package is not or maybe not full installed.

**Comment by Burhanahmedkhan** [comment]
Hey Jarus,
Yes that was the problem with package, reinstalled and restarted Kernel and it worked fine.
Thanks
