### ISSUE TITLE
authentication failed with LDAP user

### ISSUE THREAD

**Issue by paoloalba** [SAP/sqlalchemy-hana#136]
I am trying to connect to a DB instance through LDAP validated credentials, but I continuously get an authentication failed exception.
The credentials work fine with another JAVA application, and password validated credentials work fine with python.
Is the error on the dialect level or on hdbcli? Is there any parameter that can be passed in order to make the connection successful?

**Comment by kasium** [comment]
@paoloalba have you tried it without sqlalchemy-hana, so just pure hdbcli?
sqlalchemy-hana passes everything down to hdbcli, therefore authentication is handled by hdbcli itself.

Also, please provide the related python code:
* code which shows the error using sqlalchemy-hana
* code which shows that with pure hdbcli it works

**Comment by paoloalba** [comment]
I just tried with pure hdbcli, and I get the same error. If you rule out that anything extra could be passed from the dialect side, I will report the bug to the SAP community.

**Comment by kasium** [comment]
As far as I can tell you, this is the case. Please report the bug as you pointed out
