### ISSUE TITLE
Support of autoincremented key

### ISSUE THREAD

**Issue by Baschdl** [SAP/sqlalchemy-hana#2]
Sqlalchemy-hana should detect an autoincremented primary key when using `session.add(attribute1, attribute2...)` and be able to insert the attributes without specifing the value of the primary key.

sql to create table:
`CREATE COLUMN TABLE "SCHEME"."TABLE"("ID" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "ATTRIBUTE1" TYPE, "ATTRIBUTE2" TYPE...);`

**Comment by michaelkuty** [comment]
Yes but this is COLUMN table and not ROW table, for classic ROW table you should use Sequences
```
    id_seq = Sequence('id_seq', metadata=Base.metadata)
    id = Column(Integer, id_seq, primary_key=True, autoincrement=True)
```
