### ISSUE TITLE
Version 1.1 breaks backward compatibility

### ISSUE THREAD

**Issue by petersbingham** [SAP/sqlalchemy-hana#203]
I now need to provide the `use_native_boolean` when creating the sql alchemy engine.

```
        elif self.dialect == DBDialect.HANA:                                                                                                                                      |        hana_types.SECONDDATE: hana_types.SECONDDATE,
            self._engine = create_engine(self._url, **self._config.as_dict(), use_native_boolean=False)
```

otherwise I have `TINY_INT` / `BOOLEAN` type conflicts when querying DB.

`use_native_boolean` default should be `False` to retain compatibility.

**Comment by petersbingham** [comment]
Just noticed the recent major version bump, was just a couple of weeks prior to this change going in, so this is very minor and doesn't warrant a major version bump.

**Comment by kasium** [comment]
The tag view is a bit misleading. Basically it shows the latest tag which contains the commit. If you click on the three dots next to the tag, you can see all tags which contain the commit. The leftmost tag is then the initial one, which would be 1.0.0-rc1. 

The breaking change was done as part of 1.0.0, but NOT between 1.0 and 1.1. sqlalchemy-hana follows the semantic versioning convention which disallows such things

**Comment by petersbingham** [comment]
OK kasium. Sorry for the bother.
