### ISSUE TITLE
Unable to create table with ALPHANUM column

### ISSUE THREAD

**Issue by rgrenz** [SAP/sqlalchemy-hana#213]
**Describe the bug**
Creating a table with a column of type ALPHANUM fails with `AttributeError`.

**To Reproduce**
```python
from sqlalchemy import MetaData, Table, Column
from sqlalchemy_hana.types import ALPHANUM
engine = None # Engine pointed at SAP HANA

meta = MetaData()
mytab = Table("mytab", meta, Column("mycol", ALPHANUM(10)), schema="my_schema")
meta.create_all(engine) # AttributeError: 'HANATypeCompiler' object has no attribute 'visit_ALPHANUM'
```
**Expected behavior**
The table should be created and no error should be raised.

**Versions (please complete the following information):**
- `sqlalchemy` 1.4.39
- `sqlalchemy-hana` 1.2.0
- `python` 3.9
- `SAP HANA version and edition (cloud/on-prem)` 2.00.073.00.1695288802 (on-prem)

**Comment by kasium** [comment]
Thanks for the report. Looks like a oversight in the test base which should have found it. Will fix it soon

**Comment by kasium** [comment]
With #214 the issue will be fixed. The release containing it will be 1.3.0 planned to be published in the next days

**Comment by rgrenz** [comment]
Thank you for resolving this so quickly!
