### ISSUE TITLE
InvalidRequestError: Could not reflect: requested table(s) not available in Engine(hana+pyhdb:

### ISSUE THREAD

**Issue by ihenry** [SAP/sqlalchemy-hana#22]
I was trying to use the if_exists and it seems to break something.
```
from sqlalchemy import create_engine
hanaeng = create_engine('hana+pyhdb://username:password@example.de:30015')

df.to_sql('FAKE1', con=hanaeng, if_exists='replace')
```
The error given is
`InvalidRequestError: Could not reflect: requested table(s) not available in Engine(hana+pyhdb://`

**Comment by jarus** [comment]
Can you please explain what type is object `df`?

**Comment by ihenry** [comment]
Apologies, yes of course.
It is a dataframe.
A snippet of the code I used is below

```
import pandas as pd  
df = pd.read_csv('../data/Fake.News/Fake/fake.csv', usecols =['uuid','author','title','text','language','site_url'])

**Comment by jarus** [comment]
Is the issue solved after using the case-sensitive table name?

**Comment by pbdanny** [comment]
@jarus I think the best way is to try it out. Sorry, to say that as mentioned that my engine quite differ from yours.

**Comment by jarus** [comment]
@pbdanny Sure, my question was actually for @ihenry but I forgot the mention. Thanks for your comment in that thread, I hope it helps @ihenry to solve the problem.

**Comment by ihenry** [comment]
Yes, using lower a case name fixes it for me.
The table is still actually created in uppercase.
