### ISSUE TITLE
Remove "Programming Language" lables from pyproject.toml

### ISSUE THREAD

**Issue by kasium** [SAP/sqlalchemy-hana#290]
Seems like pypi can understand the python version automatically. Let's check and remove the labels

**Comment by kasium** [comment]
@maurerle you had the point in the eralchemy meeting that the classifiers are no longer needed. Do you recall if there is any documentation for this?

**Comment by maurerle** [comment]
But the license classifier is set from the version argument at least.. :)

**Comment by kasium** [comment]
Thanks for checking!
