### ISSUE TITLE
Should Column store be the default?

### ISSUE THREAD

**Issue by patbuxton** [SAP/sqlalchemy-hana#35]
Hi, I'm just working my way through a bunch of declarative code here adding 'hana_table_type' : 'Column'. Shouldn't column store be the default and you exclusively pick the row store? I'm pretty sure that most people would be using the column store as the row store is relatively featureless in comparison. Just a thought... :)

Regards, 
Pat

**Comment by jarus** [comment]
Hi Pat,

sqlalchemy-hana tries to be consistent with HANA’s default behavior. Otherwise it will create more confusion than benefit. To avoid the repeating table type definition, you could probably specify the table type within your model base class.

Best regards,
Christoph
