### ISSUE TITLE
Adding the Schema in the create_engine throws error

### ISSUE THREAD

**Issue by vipinvkmenon** [SAP/sqlalchemy-hana#4]
When adding the Schema in the create engine the connect method throws exception

`engine = create_engine('hana://user:password@host:30015/VP1',echo=True);`
`connection = engine.connect()`

It gives the error

TypeError: connect() got an unexpected keyword argument 'database'

If not the case how to pass the database Schema

**Comment by sniranjan** [comment]
any update on this?

**Comment by vipinvkmenon** [comment]
What I did was pass the connection string without the Database.
After getting the connection, I called the queries with the Schema Name in it.
<Schema>.TableName>

**Comment by jarus** [comment]
Sorry for the late response. With commit 6d8f20d130f623cbd55ef883af975880f2b8774c sqlalchemy-hana supports SAP HANA's Multi Database and the database name is defined via `hana://user:password@host:30015/database-name`. For changing the default schema, I suggest to use `MetaData.schema`.

**Comment by nawabpundit** [comment]
"""For changing the default schema, I suggest to use MetaData.schema."""
Any example please

**Comment by msardana94** [comment]
> """For changing the default schema, I suggest to use MetaData.schema.""" Any example please

@nawabpundit were you able to figure it out? I was looking for the same thing
