### ISSUE TITLE
sqlalchemy dialect for SAP R/3

### ISSUE THREAD

**Issue by amarvin** [SAP/sqlalchemy-hana#40]
Is there any plan to make a similar sqlalchemy dialect for connecting to SAP R/3 systems? Sorry that this isn't the most appropriate location to request this, but I couldn't find a better place. Maybe it could be built on top of [PyRFC](https://github.com/SAP/PyRFC).

**Comment by jarus** [comment]
I don't know about any concrete plans for such a dialect. Could you maybe explain what exactly do you have in mind? SAP R/3 systems are a layer above the database and SQLAlchemy operations only on databases.

**Comment by amarvin** [comment]
I'm not an expert on SAP R/3 systems, but I use data from it in many of my applications. It would be ideal to execute R/3 transaction codes from Python for accessing data -- do you think that's possible?

If transaction codes can't be accessed, then accessing the underlying table data (and later recreating the business logic of the transaction codes) would be the next best option. In that case, I was thinking remote function calls using PyRFC (e.g. READ_TABLE_DATA) could be an option, but it's tedious to read one table at a time with the appropriate filters. An ORM would be much better!

**Comment by jarus** [comment]
I'm sorry but there are no concrete plans to support your use-case in the near future. Especially not as part of this project.

I understand your motivation but the main goal of SAP systems is to provide functions and methods above your data. I amn't an expert but most functions and transactions are maybe wrappable with an RFC call and then usable via PyRFC.
