### ISSUE TITLE
Python Alembic migration tool with SAP HANA and sqlalchemy_hana

### ISSUE THREAD

**Issue by THM-MA** [SAP/sqlalchemy-hana#45]
I'm porting an existing Python Flask web application from a Postgres RDBMS to a SAP HANA Express database. 

SQLAlchemy works well with my SAP HANA database using the sqlalchemy_hana dialect.

However my Flask application uses the [Alembic](http://alembic.zzzcomputing.com/en/latest/) migration tool (based on SQLAlchemy) to manage the database. 

Building the database using Alembic throws an "hana" KeyError.

This is actualy rather an Alembic issue than a sqlalchemy_hana issue and i therefore posted it on [Stackoverflow](https://stackoverflow.com/questions/50159013/can-i-use-the-alembic-migration-tool-with-sap-hana-and-sqlalchemy-hana) inclusing a detailed error description.

However you may find many SQLAlchemy user managing thier database updates using Alembic migrations.

What is your oppinion on that?

**Comment by jarus** [comment]
Internally we already use alembic for our schema migrations also within Flask applications. I'm currently clarifying how and when we can share something about it.

**Comment by ThomasMarcon** [comment]
Hi Christoph,
an news on the above mentioned topic?
We are still interesetd in anything you can share.
Thx,
Thomas

**Comment by joshsullivan1** [comment]
@jarus Any update on this?

**Comment by harrycruz** [comment]
@jarus : I join the chorus in asking you about that :) Thanks!

**Comment by jarus** [comment]
I started with integrating alembic support into SQLAlchemy-HANA. The current progress is visible in the branch `alembic-preview`. Any kind of feedback is welcome.

**Comment by harrycruz** [comment]
These are great news indeed, thanks for picking this up!

**Comment by 0anton** [comment]
Hi Christoph,

I'd like to use sqlalchemy-hana with alembic db migration in internal analytic project in SAP. Is the branch your mentioned more or less complete, so we can try it? We can tolerate some glitches (also data loss) given the profits of automated db schema migration.

Anton

**Comment by kasium** [comment]
Superseded by https://github.com/SAP/sqlalchemy-hana/issues/102

In short version 1.0 will include an alembic dialect
