### ISSUE TITLE
Regex based sql queries

### ISSUE THREAD

**Issue by ankitjha97** [SAP/sqlalchemy-hana#53]
Are regex based SQL queries supported by sqlalchemy-hana?
what should be the appropriate syntax for executing this SQL query and getting back the resulting pandas dataframe?
`
SELECT ATTRIBUTE_VALUE FROM PARSING2 WHERE (ATTRIBUTE_NAME NOT REGEXP "^ADDITIONAL")
`

**Comment by jarus** [comment]
SAP HANA doesn't support this syntax. Please see the [SAP HANA documentation](https://help.sap.com/viewer/DRAFT/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/b40d483dd34d47aa9cc89b4d8a6e617e.html?q=regex) for details about using regex in SQL.
