### ISSUE TITLE
Support for JSON Document Store

### ISSUE THREAD

**Issue by robertofalk** [SAP/sqlalchemy-hana#55]
Together with the SAP HANA 2.0 SPS 01 version, it was released the support for SAP HANA JSON Document Store (also known as DocStore or Document Store). Is there any plan to support this feature as part of the sqlalchemy-hana library?

Best regards,
Roberto Falk

**Comment by jarus** [comment]
At the moment there are no concrete plans to support the SAP HANA JSON Document Store in sqlalchemy-hana but I would be happy to review and discuss a pull request for such support.

**Comment by tschnibo** [comment]
Hey, is there currently any efforts in this direction? Thank you very much!
Best Regards,
Tschnibo

**Comment by kasium** [comment]
@tschnibo I'm sorry for the latest reply. For now we don't have any plans to support it. The DocStore has a very unique syntax which is not easy to reflect in SQLAlchemy. In addition, the idea of the DocStore is to use documents. This is not meant to be used for SQLAlchemy which focuses on relation databases
