### ISSUE TITLE
Cloud Foundry Python Application calling on-premise HANA DB

### ISSUE THREAD

**Issue by kartht** [SAP/sqlalchemy-hana#59]
I am trying to establish database connectivity to on-premise HANA DB, from a python cloud foundry application. Following steps have been done:

1. TCP connection to on-premise HANA DB has been setup in SAP Cloud Connector (2.11.2). SAP cloud connector is a portable version installed on laptop, which is in the same network as HANA DB. Connection to SAP Cloud platform Sub-account is successful.

2. A connectivity service instance has been created in the SAP Cloud platform.

3. In the python application the database connection is being attempted using the following SQLALCHEMY - Create_engine statement:

create_engine('hana://DB_user:DB_pwd@virtual_host_from_scc/db',
                       connect_args = dict(host = 'virtual_host_from_scc',
                                                       port = <virtual port from scc>,
                                                       proxy_host = <on_premise_proxy_port from conn. service>,
                                                       proxy_port = <on_premise_socks5_proxy_port from conn.service>,
                                                      proxy_authorization=<JWT2 generated by XSUAA>,
                                                      CONNECTTIMEOUT = 0,
                                                      sslvalidatecertificate = 'false'))

When the application is run with debug ON, errors out at the above statement. "_**sqlalchemy.exc.DBAPIError: (hdbcli.dbapi.Error) (-10709, "Connection failed (RTE:[89006] System call 'connect' failed, rc=110:Connection timed out**_")

If I pass the virtual host and port without connect_args, errors out saying it couldn't identify the virtual host.

Any pointers in this regard would be helpful.

Thanks.

**Comment by jarus** [comment]
Sorry for the late response. Please notice that SQLAlchemy isn't covered by official SAP support. If the problem is still open, I would suggest to first try a connection through HDBCLI. If it doesn't work please reach out to the SAP Cloud Platform Support or SAP HANA Support.
