### ISSUE TITLE
Dropping primary key fails with alembic dialect

### ISSUE THREAD

**Issue by ghost** [SAP/sqlalchemy-hana#75]
HANA has a special syntax for dropping a primary key: `ALTER TABLE XXX DROP PRIMARY KEY`.
The alembic dialect currently doesn't take care of this and build a `ALTER TABLE DROP CONSTRAINT` statement.

**Comment by kasium** [comment]
We'll consider this for version 1.0.0

**Comment by kasium** [comment]
Will be fixed by https://github.com/SAP/sqlalchemy-hana/pull/131
