### ISSUE TITLE
Include readme on PyPI

### ISSUE THREAD

**Issue by amarvin** [SAP/sqlalchemy-hana#81]
The published release of `sqlachemy-hana` to PyPI currently has no project description (https://pypi.org/project/sqlalchemy-hana/). Maybe include the `README.rst` contents as the PyPI project description for future releases.

Also, the PyPI release is newer than the latest release here. Can the GitHub repo be updated to the latest release?

**Comment by kasium** [comment]
Thanks for the suggestion. A proper description will be uploaded when we publish 1.0.0
