### ISSUE TITLE
Support for JWT?

### ISSUE THREAD

**Issue by rileyhun** [SAP/sqlalchemy-hana#83]
Is there a way to authenticate to HANA using JWT? We are currently using basic authentication, but want to transition into integrating OAUTH because we don't want to enter username/password into the connection string manually for security reasons. How do we do this using SqlAlchemy? I've posted this question on Stackoverflow as well [1]

[1] [Question on SO](https://stackoverflow.com/questions/67495445/how-to-establish-python-connection-with-hana-using-oauth-jwt)
[2] [What we need to do](https://github.com/sunilwadhwa/hana-sso-jwt/blob/master/src/main/java/com/sap/startupfocus/demo/JWTDatabaseConnector.java)

**Comment by andrey-pervushin** [comment]
Up!

**Comment by kasium** [comment]
Please have a look at the available options hdbcli provides: https://help.sap.com/docs/SAP_HANA_CLIENT/f1b440ded6144a54ada97ff95dac7adf/ee592e89dcce4480a99571a4ae7a702f.html?locale=en-US. sqlchemy-hana uses hdbcli for all database communications. If hdblci supports it, then sqlalchemy-hana should support it
