### ISSUE TITLE
List package on `conda-forge` 

### ISSUE THREAD

**Issue by JakobEverdingQC** [SAP/sqlalchemy-hana#95]
Dear SAP team and maintainers @jarus,

Currently, `sqlalchemy-hana` is available from [PyPi](https://pypi.org/project/sqlalchemy-hana/). This works fine for everyone managing their dependencies with `pip` but arguably excludes those working with `conda` (or makes their lives harder, at least; see also https://pythonspeed.com/articles/conda-vs-pip/). 
It would be great if the package, ideally together with [hdbcli](https://pypi.org/project/hdbcli/) due to dependencies, could also be listed on the [conda-forge](https://conda-forge.org/) repository. 

I'd be happy to help with preparing recipes and PRs for conda-forge (more information about the process can also be found [here](https://github.com/conda-forge/staged-recipes)) - please feel free to reach out to me about this. 
Thank you for your consideration. 🙏

**Comment by kasium** [comment]
@JakobEverdingQC I'm sorry for the late reply. conda is not a release channel which is supported by SAP open source projects, therefore for now we don't have any plans to support it
